# Generated by Django 5.2.8 on 2026-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('tc_image', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('delete_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'transfer_certificates',
                'ordering': ['-created_date'],
                'managed': False,
            },
        ),
    ]
