# Generated by Django 5.2.8 on 2026-06-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfercertificate',
            options={},
        ),
    ]
