# Generated by Django 5.2.8 on 2026-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0002_alter_transfercertificate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercertificate',
            name='delete_status',
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='tc_image',
            field=models.ImageField(upload_to='tc/'),
        ),
    ]
