# Generated by Django 5.2.8 on 2026-06-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0003_remove_transfercertificate_delete_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificate',
            name='delete_status',
            field=models.IntegerField(default=0),
        ),
    ]
