# Generated by Django 5.2.8 on 2026-06-15 09:13

import tc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0004_transfercertificate_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificate',
            name='tc_image',
            field=models.ImageField(upload_to='tc/', validators=[tc.models.validate_image]),
        ),
        migrations.AlterModelTable(
            name='transfercertificate',
            table=None,
        ),
    ]
