# Generated by Django 5.2.8 on 2026-06-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0005_alter_transfercertificate_tc_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transfercertificate',
            table='transfer_certificates',
        ),
    ]
