# Generated by Django 5.2.8 on 2026-06-03 06:06

import django.db.models.deletion
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_albumimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='gid',
        ),
        migrations.AddField(
            model_name='albumimage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_images', to='gallery.galleryimage'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[gallery.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
