# Generated by Django 5.2.8 on 2026-06-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_albumimage_gid_albumimage_gallery_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumImage',
            new_name='Albums',
        ),
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='Gallery',
        ),
    ]
