# Generated by Django 5.2.8 on 2026-06-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_albumimage_albums_rename_galleryimage_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='AlbumImage',
        ),
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryImage',
        ),
    ]
