# Generated by Django 5.2.8 on 2026-06-15 06:40

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_albums_albumimage_rename_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[gallery.models.validate_image]),
        ),
    ]
